// Explicit map: our catalog product id -> Champak Steel page slug.
// Products absent from Champak are simply omitted (their pages stay untouched).
module.exports = {
  // ---------------- Pipes & Tubes ----------------
  'ss-304-pipe': 'stainless-steel-304-304l-304h-seamless-welded-pipes-tubes-manufacturer-exporter',
  'ss-310-pipe': 'stainless-steel-309-310-310s-seamless-welded-pipes-tubes-manufacturer-exporter',
  'ss-316-pipe': 'stainless-steel-316-316l-316ti-seamless-welded-pipes-tubes-manufacturer-exporter',
  'ss-317-pipe': 'stainless-steel-317-317l-seamless-welded-pipes-tubes-manufacturer-exporter',
  'ss-321-pipe': 'stainless-steel-321-321h-seamless-welded-pipes-tubes-manufacturer-exporter',
  'ss-347-pipe': 'stainless-steel-347-347h-seamless-welded-pipes-tubes-manufacturer-exporter',
  'ss-410-pipe': 'stainless-steel-410-seamless-welded-pipes-tubes-manufacturer-exporter',
  'ss-904l-pipe': 'stainless-steel-904l-seamless-welded-pipes-tubes-manufacturer-exporter',
  'duplex-s31803': 'duplex-steel-uns-s31803-2205-seamless-welded-pipes-tubes-manufacturer-exporter',
  'super-duplex-s32750': 'super-duplex-steel-uns-s32750-2507-seamless-welded-pipes-tubes-manufacturer-exporter',
  'inconel-600': 'inconel-alloy-600-601-625-718-seamless-welded-pipes-tubes-manufacturer-exporter',
  'incoloy-800': 'incoloy-alloy-800-800h-825-seamless-welded-pipes-tubes-manufacturer-exporter',
  'monel-400': 'monel-alloy-400-k500-seamless-welded-pipes-tubes-manufacturer-exporter',
  'nickel-200': 'nickel-alloy-200-201-seamless-welded-pipes-tubes-manufacturer-exporter',
  'hastelloy-c276': 'hastelloy-alloy-c22-c276-seamless-welded-pipes-tubes-manufacturer-exporter',
  'alloy-20-pipe': 'alloy-20-pipes-tubes-supplier-stockist',
  'alloy-steel-p5': 'alloy-steel-p5-seamless-welded-pipe-manufacturer',
  'alloy-steel-p9': 'alloy-steel-p9-seamless-welded-pipe-manufacturer',
  'alloy-steel-p11': 'alloy-steel-p11-seamless-welded-pipe-manufacturer',
  'alloy-steel-p12': 'alloy-steel-p12-seamless-welded-pipe-manufacturer',
  'alloy-steel-p22': 'alloy-steel-p22-seamless-welded-pipe-manufacturer',
  'alloy-steel-p91': 'alloy-steel-p91-seamless-welded-pipe-manufacturer',
  'alloy-steel-p92': 'alloy-steel-p92-seamless-welded-pipe-manufacturer',
  'ti-gr1-pipe': 'titanium-alloys-gr-1-seamless-welded-pipes-tubes-manufacturer-exporter',
  'ti-gr2-pipe': 'titanium-alloys-gr-2-seamless-welded-pipes-tubes-manufacturer-exporter',
  'ti-gr5-pipe': 'titanium-alloys-gr-5-seamless-welded-pipes-tubes-manufacturer-exporter',
  'ti-gr9-pipe': 'titanium-alloys-gr-9-seamless-welded-pipes-tubes-manufacturer-exporter',
  'cs-erw-pipe': 'carbon-steel-seamless-erw-pipes-tubes-manufacturer-exporter',
  'cs-lsaw-pipe': 'carbon-steel-saw-lsaw-hsaw-pipes-tubes-manufacturer-exporter',
  'cs-api5l-pipe': 'carbon-steel-api-5l-line-pipes-tubes-manufacturer-exporter',
  'smo-254-pipe': 'smo-254-seamless-welded-pipes-tubes-manufacturer-exporter',
  'alloy-28-pipe': 'alloy-28-seamless-welded-pipes-tubes-manufacturer-exporter',
  '253-ma-pipe': '253-ma-s30815-pipes-pipes-tubes-manufacturer-exporter',
  'cu-ni-7030': 'copper-nickel-alloy-70-30-pipes-tubes-manufacturer-exporter',
  'cu-ni-9010': 'copper-nickel-alloy-90-10-pipes-tubes-manufacturer-exporter',
  'alu-alloy-pipe': 'aluminium-alloy-2014-2024-6061-6082-7075-pipe-supplier',
  'a691-125-pipe': 'astm-a691-1-25-cr-welded-pipe-manufacturer',
  'a691-225-pipe': 'astm-a691-2-25-cr-welded-pipe-manufacturer',
  'a691-5cr-pipe': 'astm-a691-5-cr-welded-pipe-manufacturer',
  'a691-9cr-pipe': 'astm-a691-9-cr-welded-pipe-manufacturer',
  'a691-91cr-pipe': 'astm-a691-91-cr-welded-pipe-manufacturer',

  // ---------------- Plates & Sheets ----------------
  'ss-409l-sheet': '409l-sheet-plate-exporter',
  'ss-409m-sheet': '409m-sheet-plate-exporter',
  'ss-253ma-sheet': 'stainless-steel-253ma-strip-coil-sheet-plate-round-bar-exporter',
  'ss-304-sheet': 'stainless-steel-304-304l-304h-strip-coil-sheet-plate-round-bar-exporter',
  'ss-310-sheet': 'stainless-steel-310-310s-strip-coil-sheet-plate-round-bar-exporter',
  'ss-316-sheet': 'stainless-steel-316-316l-316ti-strip-coil-sheet-plate-round-bar-exporter',
  'ss-317-sheet': 'stainless-steel-317-317l-strip-coil-sheet-plate-round-bar-exporter',
  'ss-321-sheet': 'stainless-steel-321-strip-coil-sheet-plate-round-bar-exporter',
  'ss-347-sheet': 'stainless-steel-347-strip-coil-sheet-plate-round-bar-exporter',
  'ss-409-sheet': 'stainless-steel-409-strip-coil-sheet-plate-round-bar-exporter',
  'ss-410-sheet': 'stainless-steel-410-strip-coil-sheet-plate-round-bar-exporter',
  'ss-420-sheet': 'stainless-steel-420-strip-coil-sheet-plate-round-bar-exporter',
  'ss-430-sheet': 'stainless-steel-430-strip-coil-sheet-plate-round-bar-exporter',
  'ss-446-sheet': 'stainless-steel-446-strip-coil-sheet-plate-round-bar-exporter',
  'ss-904l-sheet': 'stainless-steel-904l-strip-coil-sheet-plate-round-bar-exporter',
  'duplex-s31803-sheet': 'duplex-steel-uns-s-31803-2205-strip-coil-sheet-plate-round-bar-exporter',
  'super-duplex-s32750-sheet': 'super-duplex-steel-uns-s-32750-2507-strip-coil-sheet-plate-round-bar-exporter',
  'inconel-sheet': 'inconel-alloy-600-601-625-718-sheet-plate-coils-supplier',
  'incoloy-sheet': 'incoloy-alloy-800-800h-sheet-plate-coils-supplier',
  'monel-sheet': 'monel-alloy-400-k500-sheet-plate-coils-supplier',
  'nickel-sheet': 'nickel-alloy-200-201-sheet-plate-coils-suppliers',
  'hastelloy-sheet': 'hastelloy-alloy-c22-c276-sheet-plate-coils-supplier',
  'alloy-20-sheet': 'alloy-20-sheets-plates-supplier-stockist',
  'ti-gr1-sheet': 'titanium-alloys-gr-1-plates-sheets-coils-manufacturer-exporter',
  'ti-gr2-sheet': 'titanium-alloys-gr-2-plates-sheets-coils-manufacturer-exporter',
  'ti-gr5-sheet': 'titanium-alloys-gr-5-plates-sheets-coils-manufacturer-exporter',
  'ti-gr9-sheet': 'titanium-alloys-gr-9-plates-sheets-coils-manufacturer-exporter',
  'alu-5052-sheet': 'aluminum-alloy-5052-h32-sheets-plates-stockist-supplier-exporter',
  'alu-5083-sheet': 'aluminum-alloy-5083-sheets-plates-stockist-supplier-exporter',
  'alu-5086-sheet': 'aluminum-alloy-5086-sheets-plates-stockist-supplier-exporter',
  'alu-5454-sheet': 'aluminum-alloy-5454-sheets-plates-stockist-supplier-exporter',
  'alu-6061-sheet': 'aluminum-alloy-6061-t6-sheets-plates-stockist-supplier-exporter',
  'cuni-7030-sheet': 'copper-nickel-alloy-70-30-plates-sheets-coils-manufacturer-exporter',
  'cuni-9010-sheet': 'copper-nickel-alloy-90-10-plates-sheets-coils-manufacturer-exporter',
  'cs-api-sheet': 'api-5l-x-series-plates-sheets-manufacturer-exporter',
  'cs-high-tensile-sheet': 'carbon-high-strength-high-tensile-steel-plates-sheets-manufacturer-exporter',
  'cs-mild-steel-sheet': 'mild-steel-plates-sheets-manufacturer-exporter',
  'cs-s500mc-sheet': 's500mc-hot-rolled-high-tensile-sheets-manufacturer-exporter',
  'cs-s550mc-sheet': 's550mc-hot-rolled-high-tensile-sheets-manufacturer-exporter',
  'as-grade5-sheet': 'sa-387-gr-5-sheets-plates-manufacturer-stockiest-supplier',
  'as-grade9-sheet': 'sa-387-gr-9-sheets-plates-manufacturer-stockiest-supplier',
  'as-grade11-sheet': 'sa-387-gr-11-sheets-plates-manufacturer-stockiest-supplier',
  'as-grade12-sheet': 'sa-387-gr-12-sheets-plates-manufacturer-stockiest-supplier',
  'as-grade22-sheet': 'sa-387-gr-22-sheets-plates-manufacturer-stockiest-supplier',
  'as-grade91-sheet': 'sa-387-gr-91-sheets-plates-manufacturer-stockiest-supplier',
  'smo-254-sheet': 'smo-254-sheet-plate-exporter',
  'alloy-28-sheet': 'alloy-28-sheet-plate-exporter',

  // ---------------- Round Bars ----------------
  'ss-304-bar': 'stainless-steel-304-304l-304h-round-bars-rods-manufacturer-exporter',
  'ss-310-bar': 'stainless-steel-310-310s-round-bars-rods-manufacturer-exporter',
  'ss-316-bar': 'stainless-steel-316-316l-316ti-round-bars-rods-manufacturer-exporter',
  'ss-317-bar': 'stainless-steel-317-317l-round-bars-rods-manufacturer-exporter',
  'ss-321-bar': 'stainless-steel-321-321h-round-bars-rods-manufacturer-exporter',
  'ss-347-bar': 'stainless-steel-347-347h-round-bars-rods-manufacturer-exporter',
  'ss-410-bar': 'stainless-steel-410-round-bars-rods-manufacturer-exporter',
  'ss-420-bar': 'stainless-steel-420-round-bars-rods-manufacturer-exporter',
  'ss-430-bar': 'stainless-steel-430-round-bars-rods-manufacturer-exporter',
  'ss-431-bar': 'stainless-steel-431-round-bars-rods-manufacturer-exporter',
  'ss-440a-bar': 'stainless-steel-440a-round-bars-rods-manufacturer-exporter',
  'ss-440b-bar': 'stainless-steel-440b-round-bars-rods-manufacturer-exporter',
  'ss-440c-bar': 'stainless-steel-440c-round-bars-rods-manufacturer-exporter',
  'ss-446-bar': 'stainless-steel-446-round-bars-rods-manufacturer-exporter',
  'ss-904l-bar': 'stainless-steel-904-904l-round-bars-rods-manufacturer-exporter',
  'ss-15-5ph-bar': 'stainless-steel-15-5ph-round-bars-rods-manufacturer-exporter',
  'ss-17-4ph-bar': 'stainless-steel-17-4ph-round-bars-rods-manufacturer-exporter',
  'duplex-steel-bar': 'duplex-steel-uns-s31803-2205-round-bars-rods-manufacturer-exporter',
  'super-duplex-bar': 'super-duplex-steel-uns-s32750-2507-round-bars-rods-manufacturer-exporter',
  'inconel-bar': 'inconel-alloy-600-601-625-round-bars-rods-manufacturer-exporter',
  'incoloy-bar': 'incoloy-alloy-800-800h-825-round-bars-rods-manufacturer-exporter',
  'monel-bar': 'monel-alloy-400-k500-round-bars-rods-manufacturer-exporter',
  'nickel-bar': 'nickel-alloy-200-201-round-bars-rods-manufacturer-exporter',
  'hastelloy-bar': 'hastelloy-alloy-c22-c276-round-bars-rods-manufacturer-exporter',
  'as-bar-general': 'alloy-steel-round-bars-rods-supplier-stockist',
  'as-f1-bar': 'alloy-steel-f1-round-bars-rods-supplier-stockist',
  'as-f5-bar': 'alloy-steel-f5-round-bars-rods-supplier-stockist',
  'as-f9-bar': 'alloy-steel-f9-round-bars-rods-supplier-stockist',
  'as-f11-bar': 'alloy-steel-f11-round-bars-rods-supplier-stockist',
  'as-f12-bar': 'alloy-steel-f12-round-bars-rods-supplier-stockist',
  'as-f22-bar': 'alloy-steel-f22-round-bars-rods-supplier-stockist',
  'as-f91-bar': 'alloy-steel-f91-round-bars-rods-supplier-stockist',
  'as-f92-bar': 'alloy-steel-f92-round-bars-rods-supplier-stockist',
  'alloy-20-bar': 'alloy-20-round-bars-rods-supplier-stockist',
  'brass-bar': 'brass-round-bars-rods-manufacturer-exporter',
  'tantalum-bar': 'tantalum-round-bars-rods-manufacturer-exporter',
  'cuni-7030-bar': 'copper-nickel-alloy-70-30-round-bars-rods-manufacturer-exporter',
  'cuni-9010-bar': 'copper-nickel-alloy-90-10-round-bars-rods-manufacturer-exporter',
  'cs-mild-steel-bar': 'carbon-steel-mild-steel-ship-building-round-bars-rods-manufacturer-exporter',
  'cs-high-tensile-bar': 'carbon-steel-high-strength-high-tensile-round-bars-rods-manufacturer-exporter',
  'cs-a36-bar': 'carbon-steel-a36-round-bars-rods-manufacturer-exporter',
  'cs-s355-bar': 'carbon-steel-s355j2-n-round-bars-rods-manufacturer-exporter',
  'cs-st52-bar': 'carbon-steel-st-52-round-bars-rods-manufacturer-exporter',
  'cs-en353-bar': 'carbon-steel-en-353-round-bars-rods-manufacturer-exporter',
  'ti-gr1-bar': 'titanium-alloys-gr-1-round-bars-rods-manufacturer-exporter',
  'ti-gr2-bar': 'titanium-alloys-gr-2-round-bars-rods-manufacturer-exporter',
  'ti-gr5-bar': 'titanium-alloys-gr-5-round-bars-rods-manufacturer-exporter',
  'ti-gr9-bar': 'titanium-alloys-gr-9-round-bars-rods-manufacturer-exporter',
  'ss-316lvm-bar': 'stainless-steel-316lvm-round-bars-rods-manufacturer-exporter',
  'beryllium-copper-bar': 'beryllium-copper-round-bars-rods-manufacturer-exporter',

  // ---------------- Flanges ----------------
  // Our flange SKUs bundle several grades; Champak documents one grade family per
  // page, so each maps to the first grade named in our title. Each rendered table
  // keeps Champak's own heading, so the grade it describes stays explicit.
  'ss-weld-neck-flange': 'stainless-steel-304-304l-304h-flanges-manufacturer-exporter',
  'ss-slip-on-flange': 'stainless-steel-304-304l-304h-flanges-manufacturer-exporter',
  'ss-blind-flange': 'stainless-steel-316-316l-316ti-flanges-manufacturer-exporter',
  'duplex-flanges': 'duplex-steel-uns-s31803-2205-flanges-manufacturer-exporter',
  'inconel-flanges': 'inconel-alloy-600-601-625-718-flanges-manufacturer-exporter',
  'monel-nickel-flanges': 'monel-alloy-400-k500-flanges-manufacturer-exporter',
  'hastelloy-flanges': 'hastelloy-alloy-c22-c276-flanges-manufacturer-exporter',
  'alloy-steel-flanges': 'alloy-steel-flanges-suppliers-exporters',
  'cs-flanges': 'carbon-steel-flanges-suppliers-exporters',
  'titanium-cuni-flanges': 'titanium-alloys-gr-2-flanges-manufacturer-exporter',

  // ---------------- Forged Fittings ----------------
  'ss-forged-fittings': 'stainless-steel-304-304l-304h-forged-fittings-manufacturer-exporter',
  'duplex-nickel-forged-fittings': 'duplex-steel-uns-s31803-2205-forged-fittings-manufacturer-exporter',
  'cs-as-forged-fittings': 'carbon-steel-forged-fittings-suppliers-exporters',

  // ---------------- Buttweld Fittings ----------------
  'bw-ss-elbow': 'stainless-steel-304-304l-304h-buttweld-fittings-manufacturer-exporter',

  // ---------------- Fasteners ----------------
  'ss-hex-bolts': 'stainless-steel-fasteners-manufacturer-exporter',
  'inconel-monel-fasteners': 'inconel-alloy-600-601-625-fasteners-manufacturer-exporter',
  'duplex-titanium-fasteners': 'super-duplex-steel-uns-s32750-2507-fasteners-manufacturer-exporter',

  // ---------------- Specialized Product ----------------
  'abrex-steel-plates': 'abrasion-resistant-sheets-plates-supplier-stockist',
  'abrex-400-plates': 'abrex-400-sheets-plates-supplier-stockist',
  'abrex-450-plates': 'abrex-450-sheets-plates-supplier-stockist',
  'abrex-500-plates': 'abrex-500-sheets-plates-supplier-stockist',
  'abrex-600-plates': 'abrex-600-sheets-plates-supplier-stockist',
  'rockstar-400-plates': 'rockstar-400-abrasion-resistant-sheets-plates-supplier-stockist',
  'rockstar-450-plates': 'rockstar-450-abrasion-resistant-sheets-plates-supplier-stockist',
  'rockstar-500-plates': 'rockstar-500-abrasion-resistant-sheets-plates-supplier-stockist',
  'ar-400-plates': 'ar-400-sheets-plates-supplier-stockist',
  'ar-450-plates': 'ar-450-sheets-plates-supplier-stockist',
  'ar-500-plates': 'ar-500-sheets-plates-supplier-stockist',
  'ar-600-plates': 'ar-600-sheets-plates-supplier-stockist',
  'jfe-eh-plates': 'jfe-eh-360-400-500-abrasion-resistant-sheets-plates-supplier-stockist',
  'qt-steel-plates': 'quenched-tempered-steel-sheets-plates-supplier-stockist',
  's690ql-plates': 'high-tensile-s690ql-sheets-plates-supplier-stockist',
  'weldox-700-plates': 'weldox-700-sheets-plates-supplier-stockist',
  'welten-780e-plates': 'welten780e-sheets-plates-supplier-stockist',
  'jfe-hiten-780le': 'jfe-hiten-780le-sheets-plates-supplier-stockist',
  'corten-steel-plates': 'corten-steel-sheets-plates-supplier-stockist',
  'corten-steel-a': 'corten-a-steel-sheets-plates-supplier-stockist',
  'corten-steel-b': 'corten-b-steel-sheets-plates-supplier-stockist',
  'corten-a588': 'corten-steel-grade-a588-sheets-plates-supplier-stockist',
  'corten-irsm41': 'corten-steel-irsm-41-grade-sheets-plates-supplier-stockist',
  '15mo3-steel-plates': '15mo3-steel-sheets-plates-supplier-stockist',
  '16mo3-sa204-plates': '16mo3-sa-204-steel-sheets-plates-supplier-stockist',
  'armour-steel-plates': 'armour-steel-sheets-plates-coils-supplier-stockist',
  'dsq-steel-plates': 'dsq-plates-supplier-stockist',
  'boiler-steel-plates': 'boiler-steel-plates-supplier-stockist',
  'a516-gr60-plates': 'boiler-steel-astm-a516-60-grade-plates-supplier-stockist',
  'a516-gr65-plates': 'boiler-steel-astm-a516-65-grade-plates-supplier-stockist',
  'a516-gr70-plates': 'boiler-steel-astm-a516-70-grade-plates-supplier-stockist',
  'nace-hic-plates': 'hic-resistant-steel-sheets-plates-supplier-stockist',
  'manganese-steel-plates': 'manganese-steel-sheets-plates-supplier-stockist',
  'manganese-1214-plates': '12-14-manganese-steel-plates-sheets-supplier-stockist',
  'hadfield-manganese-plates': 'hadfield-managanese-plates-sheets-supplier-stockist',
  'tiscral-sailhard-plates': 'tiscral-sailhard-plates-supplier-stockist',

  // Not on Champak Steel -> intentionally unmapped, left as-is:
  //   Gasketing Solutions (12), Structural Steel (9),
  //   socket-weld-elbow, socket-weld-tee-coupling, threaded-npt-elbow,
  //   swage-nipple-plugs (generic forged-fitting shapes, not grade pages),
  //   stud-bolts-nuts (ASTM A193 spec, no matching Champak grade page)

  // ---- Champak parity additions (catalog-fill.cjs) ----
  'stainless-steel-446-seamless-welded-pipes-tubes': 'stainless-steel-446-seamless-welded-pipes-tubes-manufacturer-exporter',
  'alloy-steel-welded-pipe': 'alloy-steel-welded-pipe-manufacturer',
  'alloy-steel-en-353-round-bars-rods': 'alloy-steel-en-353-round-bars-rods-manufacturer-exporter',
  'stainless-steel-310-310s-flanges': 'stainless-steel-310-310s-flanges-manufacturer-exporter',
  'stainless-steel-317-317l-flanges': 'stainless-steel-317-317l-flanges-manufacturer-exporter',
  'stainless-steel-321-321h-flanges': 'stainless-steel-321-321h-flanges-manufacturer-exporter',
  'stainless-steel-347-347h-flanges': 'stainless-steel-347-347h-flanges-manufacturer-exporter',
  'stainless-steel-904-904l-flanges': 'stainless-steel-904-904l-flanges-manufacturer-exporter',
  'super-duplex-steel-uns-s32750-2507-flanges': 'super-duplex-steel-uns-s32750-2507-flanges-manufacturer-exporter',
  'incoloy-alloy-800-800h-825-flanges': 'incoloy-alloy-800-800h-825-flanges-manufacturer-exporter',
  'nickel-alloy-200-201-flanges': 'nickel-alloy-200-201-flanges-manufacturer-exporter',
  'alloy-steel-f1-flanges': 'alloy-steel-f1-flanges-suppliers-exporters',
  'alloy-steel-f5-flanges': 'alloy-steel-f5-flanges-suppliers-exporters',
  'alloy-steel-f9-flanges': 'alloy-steel-f9-flanges-suppliers-exporters',
  'alloy-steel-f11-flanges': 'alloy-steel-f11-flanges-suppliers-exporters',
  'alloy-steel-f12-flanges': 'alloy-steel-f12-flanges-suppliers-exporters',
  'alloy-steel-f22-flanges': 'alloy-steel-f22-flanges-suppliers-exporters',
  'alloy-steel-f91-flanges': 'alloy-steel-f91-flanges-suppliers-exporters',
  'alloy-steel-f92-flanges': 'alloy-steel-f92-flanges-suppliers-exporters',
  'alloy-20-flanges': 'alloy-20-flanges-supplier-stockist',
  'copper-nickel-alloy-70-30-flanges': 'copper-nickel-alloy-70-30-flanges-manufacturer-exporter',
  'copper-nickel-alloy-90-10-flanges': 'copper-nickel-alloy-90-10-flanges-manufacturer-exporter',
  'titanium-alloys-gr-1-flanges': 'titanium-alloys-gr-1-flanges-manufacturer-exporter',
  'titanium-alloys-gr-5-flanges': 'titanium-alloys-gr-5-flanges-manufacturer-exporter',
  'titanium-alloys-gr-9-flanges': 'titanium-alloys-gr-9-flanges-manufacturer-exporter',
  'stainless-steel-310-310s-buttweld-fittings': 'stainless-steel-310-310s-buttweld-fittings-manufacturer-exporter',
  'stainless-steel-316-316l-316ti-buttweld-fittings': 'stainless-steel-316-316l-316ti-buttweld-fittings-manufacturer-exporter',
  'stainless-steel-317-317l-buttweld-fittings': 'stainless-steel-317-317l-buttweld-fittings-manufacturer-exporter',
  'stainless-steel-321-321h-buttweld-fittings': 'stainless-steel-321-321h-buttweld-fittings-manufacturer-exporter',
  'stainless-steel-347-347h-buttweld-fittings': 'stainless-steel-347-347h-buttweld-fittings-manufacturer-exporter',
  'stainless-steel-904l-buttweld-fittings': 'stainless-steel-904l-buttweld-fittings-manufacturer-exporter',
  'duplex-steel-uns-s31803-2205-buttweld-fittings': 'duplex-steel-uns-s31803-2205-buttweld-fittings-manufacturer-exporter',
  'super-duplex-steel-uns-s32750-2507-buttweld-fittings': 'super-duplex-steel-uns-s32750-2507-buttweld-fittings-manufacturer-exporter',
  'inconel-alloy-600-601-625-718-buttweld-fittings': 'inconel-alloy-600-601-625-718-buttweld-fittings-manufacturer-exporter',
  'incoloy-alloy-800-800h-825-buttweld-fittings': 'incoloy-alloy-800-800h-825-buttweld-fittings-manufacturer-exporter',
  'monel-alloy-400-k500-buttweld-fittings': 'monel-alloy-400-k500-buttweld-fittings-manufacturer-exporter',
  'nickel-alloy-200-201-buttweld-fittings': 'nickel-alloy-200-201-buttweld-fittings-manufacturer-exporter',
  'hastelloy-alloy-c22-c276-buttweld-fittings': 'hastelloy-alloy-c22-c276-buttweld-fittings-manufacturer-exporter',
  'carbon-steel-buttweld-fittings': 'carbon-steel-buttweld-fittings-suppliers-exporters',
  'alloy-steel-buttweld-fittings': 'alloy-steel-buttweld-fittings-suppliers-exporters',
  'alloy-20-buttweld-fittings': 'alloy-20-buttweld-fittings-supplier-stockist',
  'copper-nickel-alloy-70-30-buttweld-fittings': 'copper-nickel-alloy-70-30-buttweld-fittings-manufacturer-exporter',
  'copper-nickel-alloy-90-10-buttweld-fittings': 'copper-nickel-alloy-90-10-buttweld-fittings-manufacturer-exporter',
  'titanium-alloys-buttweld-fittings': 'titanium-alloys-buttweld-fittings-manufacturer-exporter',
  'stainless-steel-310-310s-forged-fittings': 'stainless-steel-310-310s-forged-fittings-manufacturer-exporter',
  'stainless-steel-317-317l-forged-fittings': 'stainless-steel-317-317l-forged-fittings-manufacturer-exporter',
  'stainless-steel-321-321h-forged-fittings': 'stainless-steel-321-321h-forged-fittings-manufacturer-exporter',
  'stainless-steel-347-347h-forged-fittings': 'stainless-steel-347-347h-forged-fittings-manufacturer-exporter',
  'stainless-steel-904-904l-forged-fittings': 'stainless-steel-904-904l-forged-fittings-manufacturer-exporter',
  'super-duplex-steel-uns-s32750-2507-forged-fittings': 'super-duplex-steel-uns-s32750-2507-forged-fittings-manufacturer-exporter',
  'inconel-alloy-600-601-625-718-forged-fittings': 'inconel-alloy-600-601-625-718-forged-fittings-manufacturer-exporter',
  'incoloy-alloy-800-800h-825-forged-fittings': 'incoloy-alloy-800-800h-825-forged-fittings-manufacturer-exporter',
  'monel-alloy-400-k500-forged-fittings': 'monel-alloy-400-k500-forged-fittings-manufacturer-exporter',
  'nickel-alloy-200-201-forged-fittings': 'nickel-alloy-200-201-forged-fittings-manufacturer-exporter',
  'hastelloy-alloy-c22-c276-forged-fittings': 'hastelloy-alloy-c22-c276-forged-fittings-manufacturer-exporter',
  'alloy-steel-forged-fittings': 'alloy-steel-forged-fittings-suppliers-exporters',
  'alloy-20-forged-fittings': 'alloy-20-forged-fittings-supplier-stockist',
  'copper-nickel-alloy-70-30-forged-fittings': 'copper-nickel-alloy-70-30-forged-fittings-manufacturer-exporter',
  'copper-nickel-alloy-90-10-forged-fittings': 'copper-nickel-alloy-90-10-forged-fittings-manufacturer-exporter',
  'titanium-alloys-gr-1-forged-fittings': 'titanium-alloys-gr-1-forged-fittings-manufacturer-exporter',
  'titanium-alloys-gr-2-forged-fittings': 'titanium-alloys-gr-2-forged-fittings-manufacturer-exporter',
  'titanium-alloys-gr-5-forged-fittings': 'titanium-alloys-gr-5-forged-fittings-manufacturer-exporter',
  'titanium-alloys-gr-9-forged-fittings': 'titanium-alloys-gr-9-forged-fittings-manufacturer-exporter',
  'carbon-steel-fasteners': 'carbon-steel-fasteners-manufacturer-exporter',
  'alloy-steel-fasteners': 'alloy-steel-fasteners-suppliers-exporters',
  'nickel-alloy-200-201-fasteners': 'nickel-alloy-200-201-fasteners-manufacturer-exporter',
  'duplex-steel-uns-s31803-2205-fasteners': 'duplex-steel-uns-s31803-2205-fasteners-manufacturer-exporter',
  'copper-nickel-alloy-70-30-fasteners': 'copper-nickel-alloy-70-30-fasteners-manufacturer-exporter',
  'copper-nickel-alloy-90-10-fasteners': 'copper-nickel-alloy-90-10-fasteners-manufacturer-exporter',
  'monel-alloy-400-k500-fasteners': 'monel-alloy-400-k500-fasteners-manufacturer-exporter',
  'hastelloy-alloy-c22-c276-fasteners': 'hastelloy-alloy-c22-c276-fasteners-manufacturer-exporter',
  'incoloy-alloy-800-800h-825-fasteners': 'incoloy-alloy-800-800h-825-fasteners-manufacturer-exporter',
  'alloy-20-fasteners': 'alloy-20-fasteners-supplier-stockist',
  'titanium-alloys-fasteners': 'titanium-alloys-fasteners-manufacturer-exporter',
};
